### ISSUE TITLE
Failed to began record command buffer

### ISSUE THREAD

**Issue by PolarCoords** [Kaydax/Chikara#13]
thats right, im back because i am stupid as hell.

loads the file properly then a white window

GPU: Intel iRIS Xe Graphics 

![image_2022-09-28_174332463](https://user-images.githubusercontent.com/49976368/192719239-a1ce0247-df41-4a30-a06f-a8d082b2fd9e.png)

**Comment by Kaydax** [comment]
Intel igpus don't have enough vram to start chikara with its starting buffer size. You have to compile the program yourself and change the first 2 numbers in render.h from 5000 to 2000. This is a design flaw that is not worth fixing in the current code base

**Comment by PolarCoords** [comment]
how do i compile it?
im new to coding

**Comment by Kaydax** [comment]
Use visual studio

**Comment by ieatcake515** [comment]
What gpus support vulkan? Mine is Intel HD Graphics 530

**Comment by Kaydax** [comment]
> What gpus support vulkan? Mine is Intel HD Graphics 530

https://vulkan.gpuinfo.org/

**Comment by ieatcake515** [comment]
Thanks. Does that mean mine is or isnt supported by vulkan?
