### ISSUE TITLE
Incorrect handling of sysex events. 

### ISSUE THREAD

**Issue by DixelU** [Kaydax/Chikara#15]
I recently found an issue making Chikara skip entire tracks, once met with sysex event. At first the blame was as always on SAFC that produced "corrupt" midi. But in the end - it turned out that the problem is here. 

Changes in the attached pull request: 
- Fixed sysex parsing 
  - I don't know where you found description for `0xF2`/`0xF3` events, but I suspect them to be nonexistent and it might become a potential source of problems in the future. Left the comment on them.
- Fix for v143 build tools (missing `std::wstring` in <chrono>?)
- Replaced the cringe VLV getters code with a bit more clean one, wrapped in a function (ofc taken from SAFC) 😌

- PR: https://github.com/Kaydax/Chikara/pull/14

**Comment by Kaydax** [comment]
Forgot to close, Fixed in #14
