### ISSUE TITLE
Crashing everytime

### ISSUE THREAD

**Issue by gamecube-github** [Kaydax/Chikara#16]
When drag 'n dropping midi on Chikara.exe, a window appears:
![изображение translated](https://user-images.githubusercontent.com/106277210/224542071-9c28bab8-6533-4b33-b12f-9b74684e3617.jpg)
When clicking Debug the program, it says:
![изображение](https://user-images.githubusercontent.com/106277210/224542110-19b6c622-70c0-47e3-95b4-470d5e9a1f5b.png)
What do I need to do?

**Comment by Kaydax** [comment]
First off, what are your specs including what operating system you are running.
Secondly what version did you download and what midi are you using

**Comment by Kaydax** [comment]
Closed to no response

**Comment by gamecube-github** [comment]
Sorry for no response. I rarely check Github. Specs:
Processor - Intel(R) Core(TM) i7 CPU 930 @ 2.80GHz 2.80 GHz
RAM - 16.0 GB
System type - 64-bit operating system, x64 processor
Edition - Windows 10 Pro
Version - 22H2
OS build - 19045.2486
Interoperability - Windows Feature Experience Pack 120.2212.4190.0
Downloaded Alpha 5, tested with many MIDIs

**Comment by arduano** [comment]
Does it have a GPU at all?

**Comment by gamecube-github** [comment]
I'm not on PC rn, but I remember it's NVIDIA GeForce GTX 750 Ti
