### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Chrono-byte** [Kaydax/Chikara#4]
Creating this issue to track Linux support

**Comment by Chronomly** [comment]
I might see what I can do to help with this

**Comment by Chrono-byte** [comment]
?

**Comment by Chrono-byte** [comment]
?

**Comment by SolsticeSpectrum** [comment]
Yes please. I went into the deepest rabbit hole ever trying to run black midi on Linux. My best result currently is Kiva on wine but I don't see any notes.

I don't know what to do about omnimidi tho

It has to run in desktop mode. That means I actually render Windows desktop instead of just the window.
![image](https://user-images.githubusercontent.com/38611351/215239015-c1fe7fde-1965-4465-99b4-c6a6754e0eea.png)

**Comment by arduano** [comment]
@DarkReaper231 if you don't mind compiling Rust code yourself, currently the best option is wasabi https://github.com/arduano/wasabi

It's fully cross platform, and much faster than chikara, and uses xsynth natively

**Comment by SolsticeSpectrum** [comment]
@arduano OH MY GOD

**Comment by arduano** [comment]
It's still in semi-active development and there will be many changes, but yeah we use it a lot already, but yeah because it's still in development we don't send out compiled binaries, gotta compile it yourself. Lmn if you have issues with doing that

**Comment by arduano** [comment]
Discord: Arduano#0481

**Comment by SolsticeSpectrum** [comment]
> It's still in semi-active development and there will be many changes, but yeah we use it a lot already, but yeah because it's still in development we don't send out compiled binaries, gotta compile it yourself. Lmn if you have issues with doing that

I spent several hours trying to run black midi so I am thankful there is finally something I can run natively

**Comment by Kaydax** [comment]
Chikara also runs fine under wine with both xsynth with kdmapi support and omnimidi, however its still better to use wasabi over chikara for linux since it was built to be cross platform and the successor to chikara

**Comment by SolsticeSpectrum** [comment]
> Chikara also runs fine under wine with both xsynth with kdmapi support and omnimidi, however its still better to use wasabi over chikara for linux since it was built to be cross platform and the successor to chikara

I tried running it on wine and I can confirm that it actually doesn't work. I installed omnimidi successfully but chikara was throwing errors. But I used the very old binary since running Visual Studio on wine would add whole another level of complexity to my trials.

**Comment by Kaydax** [comment]
For chikara to run under wine you have to install visual c++ 2019 in your wine environment and also override concrt140 in your winecfg. Also remember that chikara uses vulkan and needs multiple vulkan features to work properly
