### ISSUE TITLE
openGL support

### ISSUE THREAD

**Issue by imnotacoderlmao** [Kaydax/Chikara#7]
i dont have vulkan support so please add support for more gpu capabilites

**Comment by Kaydax** [comment]
Chikara is currently made to only support vulkan and its heavily tied into using it. Making it support other engines would be a huge task in itself and at that point be a whole rewrite. As it stands other graphics backends are not planned as of right now for the c++ version. Also vulkan itself is supported on a huge variety of gpus made in the last decade, so if you don't have vulkan support that means you are running on a device that would lag horribly even if chikara did support it
