### ISSUE TITLE
Chikara dont Open

### ISSUE THREAD

**Issue by Daniel-176** [Kaydax/Chikara#8]
![image](https://user-images.githubusercontent.com/78708647/122803547-20632900-d29d-11eb-83e1-3c56da0e2bc3.png)
Dont open, just close

**Comment by Kaydax** [comment]
install [this](https://aka.ms/vs/16/release/vc_redist.x64.exe)

**Comment by Kaydax** [comment]
closing issue as nothing new has been brought up
